FROM node:26-trixie-slim AS build
WORKDIR /source
RUN npm install --global pnpm@12.8.1
COPY . .
ENV BROWSER_BASE_URL=https://api.mods.maxbain.es/v2/
ENV BASE_URL=https://api.mods.maxbain.es/v2/
ENV VERCEL_URL=mods.maxbain.es
ENV VERCEL_GIT_REPO_OWNER=maxbaines
ENV VERCEL_GIT_REPO_SLUG=maxmods
ENV VERCEL_GIT_COMMIT_REF=selfhost
ENV NODE_OPTIONS=--max-old-space-size=8192
ENV FLAG_OVERRIDES='{"alwaysIgnoreErrorBanner":true,"enableMedalPromotion":false,"hidePlusPromoInUserMenu":true,"showProjectPageDownloadModalServersPromo":false,"showProjectPageCreateServersTooltip":false}'
RUN pnpm install --frozen-lockfile --filter @modrinth/frontend...
RUN pnpm i18n:coverage
RUN pnpm --filter @modrinth/frontend exec nuxi build --preset=node-server

FROM node:26-trixie-slim
RUN apt-get update && apt-get install --yes --no-install-recommends nginx dumb-init && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=build /source/apps/frontend/.output ./.output
COPY nginx.frontend.conf /etc/nginx/nginx.conf
ENV NODE_ENV=production
ENV HOST=127.0.0.1
ENV PORT=3000
EXPOSE 8080
ENTRYPOINT ["dumb-init", "--"]
CMD ["sh", "-ec", "node .output/server/index.mjs & exec nginx -g 'daemon off;'"]
